# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 16.x

    - name: Install packages
      run: npm ci

    - name: Build components
      run: npm run build

    - uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=dzeio
          -Dsonar.projectKey=dzeiocom_components
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
